Repository cerdeuk/CERTI-iOS, pull requests merged in 2025-07, with the labels that each got.

#10 [Network] #8 - 네트워크 기본 세팅
  CERTI-iOS.xcodeproj/project.pbxproj
  CERTI-iOS/Network/Base/.gitkeep
  CERTI-iOS/Network/Base/BaseResponseDTO.swift
  CERTI-iOS/Network/Base/BaseService.swift
  CERTI-iOS/Network/Base/BaseTargetType.swift
  CERTI-iOS/Network/Base/ErrorResponseDTO.swift
  CERTI-iOS/Network/Base/MoyaPlugin.swift
  CERTI-iOS/Network/Base/NetworkError.swift
  CERTI-iOS/Network/Base/NetworkService.swift
Labels: Network 📡, 한열 🧄

#14 [Network] #9 - 로그인 세팅(1)
  CERTI-iOS/Application/AppCoordinator.swift
  CERTI-iOS/Application/AppCoordinatorView.swift
  CERTI-iOS/Application/CERTI_iOSApp.swift
  CERTI-iOS/Global/Core/Auth/Error/AuthError.swift
  CERTI-iOS/Global/Core/Auth/SocialLogin/Adapters/AppleLoginAdapter.swift
  CERTI-iOS/Global/Core/Auth/SocialLogin/Adapters/KakaoLoginAdapter.swift
  CERTI-iOS/Global/Core/Auth/SocialLogin/SocialLoginServiceProtocol.swift
  CERTI-iOS/Global/Core/Auth/SocialLogin/SocialLoginType.swift
  CERTI-iOS/Global/Core/KeychainManager.swift
  CERTI-iOS/Global/Core/TokenManager.swift
  CERTI-iOS/Global/Core/TokenRefresher.swift
  CERTI-iOS/Network/Auth/AuthAPI.swift
  CERTI-iOS/Network/Auth/DTO/Response/TokenResponseDTO.swift
  CERTI-iOS/Network/Auth/TokenRefreshService.swift
  CERTI-iOS/Network/Base/BaseResponseDTO.swift
  CERTI-iOS/Network/Base/BaseService.swift
  CERTI-iOS/Network/Base/BaseTargetType.swift
  CERTI-iOS/Network/Base/NetworkService.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingView.swift
  CERTI-iOS/Presentation/Splash/View/LoginView.swift
  CERTI-iOS/Presentation/Splash/View/SplashView.swift
Labels: Network 📡, 한열 🧄

#13 [Add] #11 - 폰트 및 컬러 설정
  CERTI-iOS.xcodeproj/project.pbxproj
  CERTI-iOS/Global/Enums/.gitkeep
  CERTI-iOS/Global/Enums/CertiFont.swift
  CERTI-iOS/Global/Extensions/.gitkeep
  CERTI-iOS/Global/Extensions/View+.swift
  CERTI-iOS/Global/Modifier/.gitkeep
  CERTI-iOS/Global/Modifier/ApplyCertiFontModifier.swift
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Background/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Background/black_opacity_70.colorset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Background/black_opacity_85.colorset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Grayscale/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Grayscale/grayscale_0.colorset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Grayscale/grayscale_100.colorset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Grayscale/grayscale_200.colorset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Grayscale/grayscale_300.colorset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Grayscale/grayscale_400.colorset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Grayscale/grayscale_500.colorset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Grayscale/grayscale_600.colorset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Main/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Main/bluewhite.colorset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Main/lightblue.colorset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Main/lightpurple.colorset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Main/mainblue.colorset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Main/purpleblue.colorset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Main/purplewhite.colorset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Main/skyblue.colorset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Sub/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Sub/subyellow.colorset/Contents.json
  CERTI-iOS/Global/Resources/Fonts/Pretendard-Bold.otf
  CERTI-iOS/Global/Resources/Fonts/Pretendard-Regular.otf
  CERTI-iOS/Global/Resources/Fonts/Pretendard-SemiBold.otf
  CERTI-iOS/Info.plist
Labels: Add ✚, 상엽 🌼

#34 [Refactor] #30 - HomeView HomeViewModel 분리
  CERTI-iOS/Presentation/Home/Models/PreLicenseCardModel.swift
  CERTI-iOS/Presentation/Home/View/HomeCoordinatorView.swift
  CERTI-iOS/Presentation/Home/View/HomeView.swift
  CERTI-iOS/Presentation/Home/View/PreLicenseEditView.swift
  CERTI-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
Labels: Refactor 🏗️, 한열 🧄

#36 [Style] #31 - 추천탭 UI
  CERTI-iOS/Presentation/Home/View/HomeView.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendInterestTagBar.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendLicenseCardList.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendView.swift
  CERTI-iOS/Presentation/Recommend/ViewModel/RecommendViewModel.swift
Labels: Style 🖼️, 나연 🧸

#43 [Feat] #35 - 카카오 로그인
  CERTI-iOS/Application/AppCoordinator.swift
  CERTI-iOS/Application/CERTI_iOSApp.swift
  CERTI-iOS/Global/Core/Auth/SocialLogin/Adapters/KakaoLoginAdapter.swift
  CERTI-iOS/Global/Core/Auth/SocialLogin/SocialLoginType.swift
  CERTI-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Frame 2087329325.png
  CERTI-iOS/Global/Resources/Assets.xcassets/Login/image_login.imageset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Login/image_login.imageset/image_login (1).png
  CERTI-iOS/Global/Resources/Assets.xcassets/Login/image_login.imageset/image_login (2).png
  CERTI-iOS/Global/Resources/Assets.xcassets/Login/image_login.imageset/image_login.png
  CERTI-iOS/Global/Resources/Assets.xcassets/Login/image_login.imageset/image_login.svg
  CERTI-iOS/Global/Resources/Assets.xcassets/Login/image_login_shadow.imageset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Login/image_login_shadow.imageset/image_login_shadow.svg
  CERTI-iOS/Global/Resources/Info.plist
  CERTI-iOS/Network/Auth/AuthAPI.swift
  CERTI-iOS/Network/Auth/AuthService.swift
  CERTI-iOS/Network/Auth/DTO/Response/LoginSuccessResponseDTO.swift
  CERTI-iOS/Network/Auth/DTO/Response/SignupRequiredResponseDTO.swift
  CERTI-iOS/Network/Auth/DTO/Response/TokenResponseDTO.swift
  CERTI-iOS/Network/Base/BaseTargetType.swift
  CERTI-iOS/Network/Base/NetworkService.swift
  CERTI-iOS/Presentation/Splash/View/LoginView.swift
  CERTI-iOS/Presentation/Splash/ViewModel/LoginViewModel.swift
Labels: Feat 💻, 한열 🧄

#46 [Style] #44 - 온보딩 UI
  CERTI-iOS.xcodeproj/xcshareddata/xcschemes/CERTI-iOS.xcscheme
  CERTI-iOS/Application/AppCoordinator.swift
  CERTI-iOS/Application/AppCoordinatorView.swift
  CERTI-iOS/Global/Resources/Assets.xcassets/Image/Onboarding/onboarding_progressbar_1.imageset/step=1.svg
  CERTI-iOS/Global/Resources/Assets.xcassets/Image/Onboarding/onboarding_progressbar_2.imageset/step=2.svg
  CERTI-iOS/Global/Resources/Assets.xcassets/Image/Onboarding/onboarding_progressbar_3.imageset/step=3.svg
  CERTI-iOS/Global/Resources/Assets.xcassets/Image/Onboarding/onboarding_progressbar_4.imageset/step=4.svg
  CERTI-iOS/Global/Resources/Assets.xcassets/Image/Onboarding/onboarding_progressbar_5.imageset/step=5.svg
  CERTI-iOS/Presentation/Home/View/HomeCoordinatorView.swift
  CERTI-iOS/Presentation/Home/View/HomeView.swift
  CERTI-iOS/Presentation/Home/View/PreLicenseEditView.swift
  CERTI-iOS/Presentation/Onboarding/Coordinator/OnboardingCoordinator.swift
  CERTI-iOS/Presentation/Onboarding/Models/OnboardingMajorModel.swift
  CERTI-iOS/Presentation/Onboarding/Models/OnboardingUnivModel.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingCoordinatorView.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingGradeView.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingInfoView.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingJobCategoryView.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingMajorView.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingTrackView.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingUnivView.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingView.swift
  CERTI-iOS/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
Labels: Style 🖼️, 한열 🧄

#47 [Style] #45 - 이력서 경력사항 구현하기
  CERTI-iOS/Application/AppCoordinator.swift
  CERTI-iOS/Global/Resources/Assets.xcassets/Image/resume_list.imageset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Image/resume_list.imageset/resume_list.pdf
  CERTI-iOS/Presentation/Resume/Components/ResumeLoadMapComponent.swift
  CERTI-iOS/Presentation/Resume/Models/MyCareerModel.swift
  CERTI-iOS/Presentation/Resume/Models/MyExtracurricularActivityModel.swift
  CERTI-iOS/Presentation/Resume/View/ResumeView.swift
Labels: Style 🖼️, 상엽 🌼

#53 [Style] #50 - 토스트메세지, 모달뷰 구현
  CERTI-iOS/Global/Resources/Assets.xcassets/Colors/Background/black_opacity_85.colorset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Image/icon_warning_24.imageset/Contents.json
  CERTI-iOS/Global/Resources/Assets.xcassets/Image/icon_warning_24.imageset/icon_warning_24.svg
  CERTI-iOS/Presentation/Recommend/Components/RecommendFailToastMessage.swift
  CERTI-iOS/Presentation/Recommend/Components/RecommendSuccessToastMessage.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendCompleteModalView.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendDetailView.swift
Labels: Style 🖼️, 나연 🧸

#60 [Refactor] #51 - Recommend 뷰 뷰모델 분리
  CERTI-iOS/Presentation/Category/Components/JobCategorySegmentedControl.swift
  CERTI-iOS/Presentation/Category/View/CategoryLicenseCardList.swift
  CERTI-iOS/Presentation/Category/View/CategorySearchLicenseCardList.swift
  CERTI-iOS/Presentation/Category/View/CategorySearchView.swift
  CERTI-iOS/Presentation/Category/View/CategoryView.swift
  CERTI-iOS/Presentation/Recommend/Components/RecommendInterestTagBar.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendCompleteModalView.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendCoordinatorView.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendDetailView.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendFilterModalView.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendLicenseCardList.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendView.swift
  CERTI-iOS/Presentation/Recommend/ViewModel/RecommendViewModel.swift
Labels: Refactor 🏗️, 나연 🧸

#64 [Network] #59 - Home 사용자 정보 조회 API 연결 && 유저 탈퇴 API 연결
  CERTI-iOS/Application/AppCoordinator.swift
  CERTI-iOS/Application/AppCoordinatorView.swift
  CERTI-iOS/Global/Core/AuthManager.swift
  CERTI-iOS/Network/Auth/AuthAPI.swift
  CERTI-iOS/Network/Auth/AuthService.swift
  CERTI-iOS/Network/Base/NetworkService.swift
  CERTI-iOS/Network/User/DTO/Response/UserInfoResponseDTO.swift
  CERTI-iOS/Network/User/UserAPI.swift
  CERTI-iOS/Network/User/UserService.swift
  CERTI-iOS/Presentation/Home/View/HomeCoordinatorView.swift
  CERTI-iOS/Presentation/Home/View/HomeView.swift
  CERTI-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingInfoView.swift
  CERTI-iOS/Presentation/TabBar/View/CertiTabBarCoordinatorView.swift
Labels: Network 📡, 한열 🧄

#62 [Refactor] #57 - ResumeViewViewModel 분리
  CERTI-iOS/Global/Extensions/String+.swift
  CERTI-iOS/Presentation/Resume/Components/ResumeWriteButton.swift
  CERTI-iOS/Presentation/Resume/Models/CertificatedModel.swift
  CERTI-iOS/Presentation/Resume/Models/JobListModel.swift
  CERTI-iOS/Presentation/Resume/View/CertificateCardDetailView.swift
  CERTI-iOS/Presentation/Resume/View/MyCareerEditView.swift
  CERTI-iOS/Presentation/Resume/View/MyCareerWriteView.swift
  CERTI-iOS/Presentation/Resume/View/MyCertificateEditView.swift
  CERTI-iOS/Presentation/Resume/View/MyExtracurricularActivityEditView.swift
  CERTI-iOS/Presentation/Resume/View/MyExtracurricularActivityWriteView.swift
  CERTI-iOS/Presentation/Resume/View/ResumeCoordinatorView.swift
  CERTI-iOS/Presentation/Resume/View/ResumeView.swift
  CERTI-iOS/Presentation/Resume/ViewModel/ResumeViewModel.swift
Labels: Refactor 🏗️, 상엽 🌼

#66 [Network] #61 - 카테고리 api
  CERTI-iOS/Application/AppCoordinator.swift
  CERTI-iOS/Global/Model/LicenseCardModel.swift
  CERTI-iOS/Network/Base/BaseTargetType.swift
  CERTI-iOS/Network/Base/NetworkService.swift
  CERTI-iOS/Network/Certification/CertificationAPI.swift
  CERTI-iOS/Network/Certification/CertificationService.swift
  CERTI-iOS/Network/Certification/DTO/Response/CategoryListResponseDTO.swift
  CERTI-iOS/Presentation/Category/View/CategoryLicenseCardList.swift
  CERTI-iOS/Presentation/Category/View/CategoryView.swift
  CERTI-iOS/Presentation/Category/ViewModel/CategoryViewModel.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendDetailView.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendLicenseCardList.swift
  CERTI-iOS/Presentation/Recommend/ViewModel/RecommendViewModel.swift
Labels: Network 📡, 나연 🧸

#67 [Network] #63 - ResumeView 희망직무 조회 API 연결
  CERTI-iOS/Network/Base/NetworkService.swift
  CERTI-iOS/Network/Job/DTO/Response/JobListResponseDTO.swift
  CERTI-iOS/Network/Job/JobAPI.swift
  CERTI-iOS/Network/Job/JobService.swift
  CERTI-iOS/Presentation/Resume/View/ResumeView.swift
  CERTI-iOS/Presentation/Resume/ViewModel/ResumeViewModel.swift
Labels: Network 📡, 상엽 🌼

#74 [Network] #71 - 취득 예정 API 연결
  CERTI-iOS/Network/Base/NetworkService.swift
  CERTI-iOS/Network/Certification/DTO/Response/CertificationInfoResponseDTO.swift
  CERTI-iOS/Network/Home/DTO/Response/PreCertificationInfoResponseDTO.swift
  CERTI-iOS/Network/Home/HomeAPI.swift
  CERTI-iOS/Network/Home/HomeService.swift
  CERTI-iOS/Presentation/Home/Models/PreLicenseCardModel.swift
  CERTI-iOS/Presentation/Home/View/HomeCoordinatorView.swift
  CERTI-iOS/Presentation/Home/View/HomeView.swift
  CERTI-iOS/Presentation/Home/View/PreLicenseEditView.swift
  CERTI-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
Labels: Network 📡, 한열 🧄

#76 [Refector] #68 - ResumeView 취득한 자격증 로직 변경
  CERTI-iOS/Presentation/Resume/Components/CeritificateCardComponent.swift
  CERTI-iOS/Presentation/Resume/Components/TagChipMini.swift
  CERTI-iOS/Presentation/Resume/Models/CertificatedModel.swift
  CERTI-iOS/Presentation/Resume/View/CertificateCardDetailView.swift
  CERTI-iOS/Presentation/Resume/View/MyCertificateEditView.swift
  CERTI-iOS/Presentation/Resume/View/ResumeView.swift
Labels: Refactor 🏗️, 상엽 🌼

#80 [Network] #77 - 취득한 자격증 조회 API 연결
  CERTI-iOS/Network/Acquisition/AcquisitionAPI.swift
  CERTI-iOS/Network/Acquisition/AcquisitionService.swift
  CERTI-iOS/Network/Acquisition/DTO/Response/AcquisitionListResponseDTO.swift
  CERTI-iOS/Network/Base/NetworkService.swift
  CERTI-iOS/Presentation/Resume/Components/CeritificateCardComponent.swift
  CERTI-iOS/Presentation/Resume/Models/CertificatedModel.swift
  CERTI-iOS/Presentation/Resume/View/ResumeView.swift
  CERTI-iOS/Presentation/Resume/ViewModel/ResumeViewModel.swift
Labels: Network 📡, 상엽 🌼

#84 [Network] #83 - 추천탭 api, 희망직무 api 구현
  CERTI-iOS/Network/Certification/CertificationService.swift
  CERTI-iOS/Network/Certification/DTO/Response/RecommendCertificationResponseDTO.swift
  CERTI-iOS/Network/Job/DTO/Request/EditJobRequestDTO.swift
  CERTI-iOS/Network/Job/JobAPI.swift
  CERTI-iOS/Network/Job/JobService.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendFilterModalView.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendLicenseCardList.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendView.swift
  CERTI-iOS/Presentation/Recommend/ViewModel/RecommendViewModel.swift
Labels: Network 📡, 나연 🧸

#86 [Network] #81 경력사항 리스트 조회 API 연결
  CERTI-iOS/Network/Base/NetworkService.swift
  CERTI-iOS/Network/Careers/CareersAPI.swift
  CERTI-iOS/Network/Careers/CareersService.swift
  CERTI-iOS/Network/Careers/DTO/Response/CareersListResponseDTO.swift
  CERTI-iOS/Presentation/Resume/Components/ResumeActivityListComponent.swift
  CERTI-iOS/Presentation/Resume/View/MyCareerEditView.swift
  CERTI-iOS/Presentation/Resume/View/ResumeView.swift
  CERTI-iOS/Presentation/Resume/ViewModel/ResumeViewModel.swift
Labels: Network 📡, 상엽 🌼

#88 [Network] #87 - 대내외 활동 리스트 조회 API 연결
  CERTI-iOS/Network/Activity/ActivityAPI.swift
  CERTI-iOS/Network/Activity/ActivityService.swift
  CERTI-iOS/Network/Activity/DTO/Response/ActivityListResponseDTO.swift
  CERTI-iOS/Network/Base/NetworkService.swift
  CERTI-iOS/Presentation/Resume/View/MyExtracurricularActivityEditView.swift
  CERTI-iOS/Presentation/Resume/View/ResumeView.swift
  CERTI-iOS/Presentation/Resume/ViewModel/ResumeViewModel.swift
Labels: Network 📡, 상엽 🌼

#90 [Feat] #79 - 로딩뷰 연결 & 탭바 로직 수정
  CERTI-iOS/Application/AppCoordinator.swift
  CERTI-iOS/Global/Components/CertiLoadingView.swift
  CERTI-iOS/Global/Manager/AuthManager.swift
  CERTI-iOS/Network/Base/BaseTargetType.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingInfoView.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingMajorView.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingUnivView.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendCoordinatorView.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendFilterModalView.swift
  CERTI-iOS/Presentation/Recommend/ViewModel/RecommendViewModel.swift
  CERTI-iOS/Presentation/Resume/View/ResumeCoordinatorView.swift
  CERTI-iOS/Presentation/Resume/View/ResumeView.swift
  CERTI-iOS/Presentation/Resume/ViewModel/ResumeViewModel.swift
Labels: Feat 💻, 한열 🧄

#91 [Network] #89 - 취득한 자격증 상세 조회 API 연결
  CERTI-iOS/Network/Acquisition/AcquisitionAPI.swift
  CERTI-iOS/Network/Acquisition/AcquisitionService.swift
  CERTI-iOS/Network/Acquisition/DTO/Response/AcquisitionDetailResponseDTO.swift
  CERTI-iOS/Presentation/Resume/View/CertificateCardDetailView.swift
  CERTI-iOS/Presentation/Resume/View/MyCertificateEditView.swift
  CERTI-iOS/Presentation/Resume/View/ResumeView.swift
  CERTI-iOS/Presentation/Resume/ViewModel/ResumeViewModel.swift
Labels: Network 📡, 상엽 🌼

#96 [Network] #95 - 경력사항 삭제 API 연동
  CERTI-iOS/Network/Activity/DTO/Response/ActivityListResponseDTO.swift
  CERTI-iOS/Network/Careers/CareersAPI.swift
  CERTI-iOS/Network/Careers/CareersService.swift
  CERTI-iOS/Network/Careers/DTO/Response/CareersListResponseDTO.swift
  CERTI-iOS/Presentation/Resume/Models/ResumeModel.swift
  CERTI-iOS/Presentation/Resume/View/MyCareerEditView.swift
  CERTI-iOS/Presentation/Resume/ViewModel/ResumeViewModel.swift
Labels: Network 📡, 상엽 🌼

#112 [Fix] #108 - 앱잼 QA 반영(카테고리 화면)
  CERTI-iOS/Global/Components/LicenseCardItem.swift
  CERTI-iOS/Presentation/Category/Components/FavoriteFilterToggleButton.swift
Labels: Fix 🔨, 나연 🧸

#118 [Fix] #117 - 온보딩 및 유저 관리 로직 수정
  CERTI-iOS/Application/AppCoordinator.swift
Labels: Network 📡, 한열 🧄

#120 [Fix] #116 - 앱잼 QA 반영 - 자격증 세부 화면
  CERTI-iOS/Network/Base/BaseService.swift
  CERTI-iOS/Presentation/CertificateDetail/View/CertificateDetailView.swift
  CERTI-iOS/Presentation/CertificateDetail/View/CertificationDetailCompleteModalView.swift
  CERTI-iOS/Presentation/CertificateDetail/ViewModel/CertificateDetailViewModel.swift
Labels: Fix 🔨, 나연 🧸

#122 [Fix] #109 - 앱잼 QA 반영 - 이력서 뷰
  CERTI-iOS/Network/Acquisition/DTO/Response/AcquisitionDetailResponseDTO.swift
  CERTI-iOS/Network/Acquisition/DTO/Response/AcquisitionListResponseDTO.swift
  CERTI-iOS/Presentation/Resume/Components/CeritificateCardComponent.swift
  CERTI-iOS/Presentation/Resume/Components/CharLimitTextField.swift
  CERTI-iOS/Presentation/Resume/Components/ResumeActivityListComponent.swift
  CERTI-iOS/Presentation/Resume/Components/ResumeWriteButton.swift
  CERTI-iOS/Presentation/Resume/Models/CertificatedDetailModel.swift
  CERTI-iOS/Presentation/Resume/Models/CertificatedListModel.swift
  CERTI-iOS/Presentation/Resume/Models/CertificatedModel.swift
  CERTI-iOS/Presentation/Resume/View/CertificateCardDetailView.swift
  CERTI-iOS/Presentation/Resume/View/MyCareerEditView.swift
  CERTI-iOS/Presentation/Resume/View/MyCareerWriteView.swift
  CERTI-iOS/Presentation/Resume/View/MyCertificateEditView.swift
  CERTI-iOS/Presentation/Resume/View/MyExtracurricularActivityWriteView.swift
  CERTI-iOS/Presentation/Resume/View/ResumeView.swift
  CERTI-iOS/Presentation/Resume/ViewModel/ResumeViewModel.swift
Labels: Fix 🔨, 상엽 🌼

#121 [Feat] #119 - 뒤로가기 스와이프 활성화
  CERTI-iOS/Global/Extensions/UINavigationController+.swift
  CERTI-iOS/Global/Extensions/View+.swift
  CERTI-iOS/Global/Manager/SwipePopGestureManager.swift
Labels: Feat 💻, 한열 🧄

#130 [Fix] #127 - 추천 뷰 필터 즉각 반영
  CERTI-iOS/Global/Extensions/String+.swift
  CERTI-iOS/Presentation/Home/Components/PreLicenseCard.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendView.swift
  CERTI-iOS/Presentation/Resume/View/ResumeView.swift
Labels: Fix 🔨, 한열 🧄
