Repository cerdeuk/CERTI-iOS, pull requests merged in 2025-08, with the labels that each got.

#144 [Refactor] #143 - 클린 아키텍처 리팩토링(Job)
  CERTI-iOS/Application/DIContainer/AppDIContainer.swift
  CERTI-iOS/Data/Network/Job/DTO/Response/JobListResponseDTO.swift
  CERTI-iOS/Data/Network/Job/JobService.swift
  CERTI-iOS/Data/Repositories/DefaultJobRepository.swift
  CERTI-iOS/Domain/Entities/JobEntity.swift
  CERTI-iOS/Domain/Interfaces/Repositories/JobRepository.swift
  CERTI-iOS/Domain/UseCases/EditJobUseCase.swift
  CERTI-iOS/Domain/UseCases/FetchJobUseCase.swift
  CERTI-iOS/Presentation/Recommend/ViewModel/RecommendViewModel.swift
  CERTI-iOS/Presentation/Resume/ViewModel/ResumeViewModel.swift
Labels: Refactor 🏗️, 나연 🧸

#147 [Refactor] #140 - 클린 아키텍처 리팩토링
  CERTI-iOS/Application/Coordinator/AppCoordinatorView.swift
  CERTI-iOS/Application/DIContainer/AppDIContainer.swift
  CERTI-iOS/Data/Network/Auth/AuthService.swift
  CERTI-iOS/Data/Network/Auth/DTO/Request/SignupRequestDTO.swift
  CERTI-iOS/Data/Network/Auth/DTO/Response/LoginSuccessResponseDTO.swift
  CERTI-iOS/Data/Network/Auth/DTO/Response/SignupRequiredResponseDTO.swift
  CERTI-iOS/Data/Network/Auth/DTO/Response/SignupSuccessResponseDTO.swift
  CERTI-iOS/Data/Network/Home/DTO/Response/FavoriteCertificationResponseDTO.swift
  CERTI-iOS/Data/Network/Home/DTO/Response/PreCertificationInfoResponseDTO.swift
  CERTI-iOS/Data/Network/Onboarding/DTO/Response/MajorListResponseDTO.swift
  CERTI-iOS/Data/Network/Onboarding/DTO/Response/UnivListResponseDTO.swift
  CERTI-iOS/Data/Network/User/DTO/Response/UserInfoResponseDTO.swift
  CERTI-iOS/Data/Repositories/DefaultAuthRepository.swift
  CERTI-iOS/Data/Repositories/DefaultHomeRepository.swift
  CERTI-iOS/Data/Repositories/DefaultOnboardingRepository.swift
  CERTI-iOS/Data/Repositories/DefaultUserRepository.swift
  CERTI-iOS/Domain/Entities/Auth/LoginSuccessResponseEntity.swift
  CERTI-iOS/Domain/Entities/Auth/SignupEntity.swift
  CERTI-iOS/Domain/Entities/MajorListEntity.swift
  CERTI-iOS/Domain/Entities/UniversityListEntity.swift
  CERTI-iOS/Domain/Entities/UserInfoEntity.swift
  CERTI-iOS/Domain/Interfaces/Repositories/AuthRepository.swift
  CERTI-iOS/Domain/Interfaces/Repositories/OnboardingRepository.swift
  CERTI-iOS/Domain/Interfaces/Repositories/UserRepository.swift
  CERTI-iOS/Domain/UseCases/Auth/LoginUseCase.swift
  CERTI-iOS/Domain/UseCases/Auth/SignUpUseCase.swift
  CERTI-iOS/Domain/UseCases/Auth/WithDrawUseCase.swift
  CERTI-iOS/Domain/UseCases/FetchMajorListUseCase.swift
  CERTI-iOS/Domain/UseCases/FetchUnivListUseCase.swift
  CERTI-iOS/Domain/UseCases/FetchUserInfoUseCase.swift
  CERTI-iOS/Global/Core/TokenRefresher.swift
  CERTI-iOS/Global/Manager/AuthManager.swift
  CERTI-iOS/Presentation/Category/ViewModel/CategoryViewModel.swift
  CERTI-iOS/Presentation/CertificateDetail/ViewModel/CertificateDetailViewModel.swift
  CERTI-iOS/Presentation/Home/Factory/HomeFactory.swift
  CERTI-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  CERTI-iOS/Presentation/Onboarding/Factory/OnboardingFactory.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingCoordinatorView.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingGradeView.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingInfoView.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingJobCategoryView.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingMajorView.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingTrackView.swift
  CERTI-iOS/Presentation/Onboarding/View/OnboardingUnivView.swift
  CERTI-iOS/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
  CERTI-iOS/Presentation/Recommend/ViewModel/RecommendViewModel.swift
  CERTI-iOS/Presentation/Resume/ViewModel/ResumeViewModel.swift
  CERTI-iOS/Presentation/Splash/ViewModel/LoginViewModel.swift
Labels: Refactor 🏗️, 한열 🧄

#150 [Refactor] #149 - Clean Architecture Refactoring(Careers, Activity)
  CERTI-iOS/Application/DIContainer/AppDIContainer.swift
  CERTI-iOS/Data/Network/Acquisition/DTO/Response/AcquisitionDetailResponseDTO.swift
  CERTI-iOS/Data/Network/Acquisition/DTO/Response/AcquisitionListResponseDTO.swift
  CERTI-iOS/Data/Network/Activity/DTO/Response/ActivityListResponseDTO.swift
  CERTI-iOS/Data/Network/Careers/DTO/Response/CareersListResponseDTO.swift
  CERTI-iOS/Data/Repositories/DefaultAcquisitionRepository.swift
  CERTI-iOS/Data/Repositories/DefaultActivityRepository.swift
  CERTI-iOS/Data/Repositories/DefaultCareersRepository.swift
  CERTI-iOS/Domain/Entities/Acquisition/AcquisitionDetailEntity.swift
  CERTI-iOS/Domain/Entities/Acquisition/AcquisitionListEntity.swift
  CERTI-iOS/Domain/Entities/ResumeEntity.swift
  CERTI-iOS/Domain/Interfaces/Repositories/AcquisitionRepository.swift
  CERTI-iOS/Domain/Interfaces/Repositories/ActivityRepository.swift
  CERTI-iOS/Domain/Interfaces/Repositories/CareersRepository.swift
  CERTI-iOS/Domain/UseCases/Acquisition/AddAcquisitionUseCase.swift
  CERTI-iOS/Domain/UseCases/Acquisition/DeleteAcquisitionUseCase.swift
  CERTI-iOS/Domain/UseCases/Acquisition/FetchAcquisitionDetailUseCase.swift
  CERTI-iOS/Domain/UseCases/Acquisition/FetchAcquisitionListUseCase.swift
  CERTI-iOS/Domain/UseCases/Activity/AddActivityUseCase.swift
  CERTI-iOS/Domain/UseCases/Activity/DeleteActivityUseCase.swift
  CERTI-iOS/Domain/UseCases/Activity/FetchActivityListUseCase.swift
  CERTI-iOS/Domain/UseCases/Careers/AddCareersUseCase.swift
  CERTI-iOS/Domain/UseCases/Careers/DeleteCareersUseCase.swift
  CERTI-iOS/Domain/UseCases/Careers/FetchCareersListUseCase.swift
  CERTI-iOS/Presentation/CertificateDetail/ViewModel/CertificateDetailViewModel.swift
  CERTI-iOS/Presentation/Resume/Components/CeritificateCardComponent.swift
  CERTI-iOS/Presentation/Resume/Components/ResumeActivityListComponent.swift
  CERTI-iOS/Presentation/Resume/Factory/ResumeFactory.swift
  CERTI-iOS/Presentation/Resume/Models/CertificatedModel.swift
  CERTI-iOS/Presentation/Resume/Models/ResumeModel.swift
  CERTI-iOS/Presentation/Resume/View/MyCareerWriteView.swift
  CERTI-iOS/Presentation/Resume/View/MyExtracurricularActivityWriteView.swift
  CERTI-iOS/Presentation/Resume/View/ResumeCoordinatorView.swift
  CERTI-iOS/Presentation/Resume/ViewModel/ResumeViewModel.swift
  CERTI-iOS/Presentation/TabBar/View/CertiTabBarCoordinatorView.swift
Labels: Refactor 🏗️, 상엽 🌼

#151 [Refactor] #145 - 클린아키텍처 리팩토링(Certification)
  CERTI-iOS/Application/DIContainer/AppDIContainer.swift
  CERTI-iOS/Data/Network/Certification/CertificationAPI.swift
  CERTI-iOS/Data/Network/Certification/DTO/Response/CategoryListResponseDTO.swift
  CERTI-iOS/Data/Network/Certification/DTO/Response/CertificationDetailResponseDTO.swift
  CERTI-iOS/Data/Network/Certification/DTO/Response/CertificationInfoResponseDTO.swift
  CERTI-iOS/Data/Network/Certification/DTO/Response/RecommendCertificationResponseDTO.swift
  CERTI-iOS/Data/Network/Certification/DTO/Response/SearchCertificationResponseDTO.swift
  CERTI-iOS/Data/Network/Home/DTO/Response/PreCertificationInfoResponseDTO.swift
  CERTI-iOS/Data/Network/Job/DTO/Response/JobListResponseDTO.swift
  CERTI-iOS/Data/Repositories/DefaultCertificationRepository.swift
  CERTI-iOS/Data/Repositories/DefaultJobRepository.swift
  CERTI-iOS/Domain/Entities/Certification/CertificationDetailEntity.swift
  CERTI-iOS/Domain/Entities/Certification/CertificationsEntity.swift
  CERTI-iOS/Domain/Entities/Certification/RecommendCertificationEntity.swift
  CERTI-iOS/Domain/Entities/JobEntity.swift
  CERTI-iOS/Domain/Interfaces/Repositories/CertificationRepository.swift
  CERTI-iOS/Domain/UseCases/Certification/FetchCategoryUseCase.swift
  CERTI-iOS/Domain/UseCases/Certification/FetchCertificationDetailUseCase.swift
  CERTI-iOS/Domain/UseCases/Certification/FetchRecommendUseCase.swift
  CERTI-iOS/Domain/UseCases/Certification/SearchCertificationUseCase.swift
  CERTI-iOS/Domain/UseCases/Certification/SwitchFavoriteUseCase.swift
  CERTI-iOS/Presentation/Category/Factory/CategoryFactory.swift
  CERTI-iOS/Presentation/Category/View/CategoryCoordinatorView.swift
  CERTI-iOS/Presentation/Category/ViewModel/CategoryViewModel.swift
  CERTI-iOS/Presentation/CertificateDetail/Factory/CertificateDetailFactory.swift
  CERTI-iOS/Presentation/CertificateDetail/ViewModel/CertificateDetailViewModel.swift
  CERTI-iOS/Presentation/Home/Models/RecommendLicenseCardModel.swift
  CERTI-iOS/Presentation/Home/View/HomeCoordinatorView.swift
  CERTI-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  CERTI-iOS/Presentation/Recommend/Factory/RecommendFactory.swift
  CERTI-iOS/Presentation/Recommend/Model/JobFieldModel.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendCoordinatorView.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendFilterModalView.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendView.swift
  CERTI-iOS/Presentation/Recommend/ViewModel/RecommendViewModel.swift
  CERTI-iOS/Presentation/TabBar/View/CertiTabBarCoordinatorView.swift
Labels: Refactor 🏗️, 나연 🧸

#158 [Refactor] #153 - 코디네이터 붙이기
  CERTI-iOS/Application/DIContainer/AppDIContainer.swift
  CERTI-iOS/Data/Repositories/DefaultAcquisitionRepository.swift
  CERTI-iOS/Data/Repositories/DefaultHomeRepository.swift
  CERTI-iOS/Domain/Interfaces/Repositories/AcquisitionRepository.swift
  CERTI-iOS/Domain/Interfaces/Repositories/HomeRepository.swift
  CERTI-iOS/Domain/UseCases/Acquisition/AddAcquisitionUseCase.swift
  CERTI-iOS/Domain/UseCases/AddPreCertificationUseCase.swift
  CERTI-iOS/Presentation/Category/Coordinator/CategoryCoordinator.swift
  CERTI-iOS/Presentation/Category/View/CategoryCoordinatorView.swift
  CERTI-iOS/Presentation/Category/View/CategoryLicenseCardList.swift
  CERTI-iOS/Presentation/Category/View/CategorySearchLicenseCardList.swift
  CERTI-iOS/Presentation/Category/View/CategorySearchView.swift
  CERTI-iOS/Presentation/Category/View/CategoryView.swift
  CERTI-iOS/Presentation/Category/ViewModel/CategoryViewModel.swift
  CERTI-iOS/Presentation/CertificateDetail/Factory/CertificateDetailFactory.swift
  CERTI-iOS/Presentation/CertificateDetail/View/CertificateDetailView.swift
  CERTI-iOS/Presentation/CertificateDetail/ViewModel/CertificateDetailViewModel.swift
  CERTI-iOS/Presentation/Home/Factory/HomeFactory.swift
  CERTI-iOS/Presentation/Home/View/HomeCoordinatorView.swift
  CERTI-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  CERTI-iOS/Presentation/Recommend/Coordinator/RecommendCoordinator.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendCoordinatorView.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendLicenseCardList.swift
  CERTI-iOS/Presentation/Recommend/View/RecommendView.swift
  CERTI-iOS/Presentation/Recommend/ViewModel/RecommendViewModel.swift
  CERTI-iOS/Presentation/TabBar/View/CertiTabBarCoordinatorView.swift
Labels: Refactor 🏗️, 나연 🧸
